server:
  port: 8090

spring:
  data:
    mongodb:
      username: dmhoang
      password: dmhoang
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin